import Foundation

@main struct DriveStateTests {
    static func main() {
        var drive = DriveState()
        assert(!drive.begin(), "Disconnected scenes must not start the microphone")
        drive.connect()
        assert(!drive.begin(), "A connected background scene must not start")
        drive.activate()
        assert(drive.automaticStartAvailable)
        assert(drive.begin())
        assert(!drive.begin(), "Duplicate activation must not start a second session")
        drive.didBrief()
        drive.resign()
        assert(!drive.running && !drive.begin())
        drive.activate()
        assert(!drive.automaticStartAvailable, "Returning from Siri or Maps must require an explicit Talk tap")
        assert(drive.begin() && drive.briefed, "Returning from Maps must not repeat the briefing")
        drive.disconnect()
        assert(!drive.running && !drive.connected)
        drive.connect(); drive.activate()
        assert(drive.automaticStartAvailable)
        assert(drive.begin() && !drive.briefed, "A new drive gets its own greeting")
        var activatedFirst = DriveState()
        activatedFirst.activate()
        assert(!activatedFirst.begin(), "Activation alone cannot record without a CarPlay connection")
        activatedFirst.connect()
        assert(activatedFirst.automaticStartAvailable && activatedFirst.begin(),
               "Activation before interface connection must not leave Talk inert")
        var alreadyActive = DriveState()
        alreadyActive.connect(isActive: true)
        assert(alreadyActive.begin(), "An already-active scene can start when its interface arrives")
        var tapped = DriveState()
        assert(!tapped.beginFromTap(), "A stale button after disconnect cannot start")
        tapped.connect()
        assert(!tapped.begin(), "Connecting in the background still must not auto-start")
        assert(tapped.beginFromTap(), "A visible Talk button must work without an activation callback")
        assert(!tapped.beginFromTap(), "Repeated Talk taps cannot start overlapping sessions")
        tapped.didBrief()
        tapped.resign()
        tapped.activate()
        assert(!tapped.automaticStartAvailable, "Interruption must still require a driver tap")
        assert(tapped.beginFromTap() && tapped.briefed, "Manual resume keeps the existing briefing")
        tapped.disconnect()
        assert(!tapped.beginFromTap(), "Disconnected templates cannot reopen the microphone")
        assert(DriveState.mapsURL(latitude: .nan, longitude: 0) == nil)
        assert(DriveState.mapsURL(latitude: 0, longitude: 181) == nil)
        let url = DriveState.mapsURL(latitude: -31.95, longitude: 115.86)!
        let parts = URLComponents(url: url, resolvingAgainstBaseURL: false)!
        assert(parts.host == "maps.apple.com" && parts.scheme == "https")
        assert(parts.queryItems?.first?.value == "-31.95,115.86")
        assert(parts.queryItems?.last?.value == "d")
        print("Drive lifecycle and Maps handoff checks passed")
    }
}
