// Regenerates Haru/Resources/stage.html from the desktop's phone page, so the
// app shows the same SVG avatar the page does — crossfade, idle float, a
// wandering gaze, a blink calendar, eyes found by geometry — with no second
// copy of that code to keep in step. Run whenever electron/webpage.ts or
// emotions.ts change on the desktop side:
//
//   node scripts/sync-avatar.mjs [path/to/haru-desktop]
//
// The avatar fetches /emotions/<name>.svg itself; in the app that request
// goes through haru-stage://, which the app answers from her server.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const desktop = resolve(process.argv[2] ?? '../haru-desktop');
const built = mkdtempSync(join(tmpdir(), 'haru-avatar-'));
// The tables live in TypeScript; the desktop's own compiler turns that one
// file into JavaScript this script can import (its only import is a type).
execFileSync(join(desktop, 'node_modules/.bin/tsc'), [
  '--outDir', built, '--module', 'es2022', '--target', 'es2022', '--moduleResolution', 'bundler',
  '--lib', 'es2022,dom', '--skipLibCheck', '--noEmitOnError', 'false', join(desktop, 'electron/emotions.ts'),
], { stdio: 'inherit' });
const emotions = await import(pathToFileURL(join(built, 'emotions.js')).href);
const { DEFAULT_TRANSITION_MS, EASE_OUT_CSS, emotionConfig, HARU_EMOTIONS, MOOD_TO_EMOTION } = emotions;
const source = readFileSync(resolve(desktop, 'electron/webpage.ts'), 'utf8');

/** The text of a template literal in the source, evaluated with the page's own tables in scope. */
function evaluate(template) {
  const fill = new Function('DEFAULT_TRANSITION_MS', 'EASE_OUT_CSS', 'emotionConfig', 'HARU_EMOTIONS', 'MOOD_TO_EMOTION', 'return `' + template + '`');
  return fill(DEFAULT_TRANSITION_MS, EASE_OUT_CSS, emotionConfig, HARU_EMOTIONS, MOOD_TO_EMOTION);
}
function slice(from, to, label) {
  const start = source.indexOf(from);
  if (start < 0) throw new Error(`could not find the start of the ${label}`);
  const end = source.indexOf(to, start + from.length);
  if (end < 0) throw new Error(`could not find the end of the ${label}`);
  return source.slice(start + from.length, end + (to.startsWith('\n') ? 0 : to.length));
}

const avatar = evaluate(slice('const AVATAR = `', '\n`;', 'avatar script'));
const css = evaluate(slice('  /* Her, on stage:', '#avatar .face { transition:none !important; } }', 'avatar styles'));
if (!avatar.includes('window.haruAvatar')) throw new Error('the avatar script does not look right');

const html = `<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<!-- Generated by scripts/sync-avatar.mjs from haru-desktop/electron/webpage.ts. Do not edit by hand. -->
<style>
html, body { margin:0; height:100%; background:transparent; overflow:hidden; -webkit-user-select:none; -webkit-touch-callout:none; }
body { display:flex; align-items:center; justify-content:center; }
${css}
#stage { padding:0; --avatar-size:min(100vw, 100vh); transition:transform .3s ease; }
</style>
<section id="stage"></section>
<script>
(() => {
  const tell = (message) => { try { window.webkit.messageHandlers.stage.postMessage(message); } catch (e) {} };
  window.addEventListener('error', (e) => tell({ event: 'failed', why: (e && e.message) || 'a script error' }));
  const clamp = (v, lo, hi) => (v < lo ? lo : v > hi ? hi : v);
  // The app speaks to window.haruStage; this hands it on to the page's
  // avatar. Zoom scales her box; lift moves her up by a share of the stage.
  let framing = { zoom: 1, lift: 0 };
  const applyFraming = () => {
    const host = document.getElementById('stage');
    if (!host) return;
    host.style.setProperty('--avatar-size', 'calc(min(100vw, 100vh) * ' + framing.zoom + ')');
    host.style.transform = 'translateY(' + (-framing.lift * 100).toFixed(1) + '%)';
  };
  window.haruStage = {
    express: (name) => { const a = window.haruAvatar; if (a && name) a.express(name); },
    attend: (why, ms) => {
      const a = window.haruAvatar;
      if (!a) return;
      if (why === 'thinking') a.think();
      else if (why === 'talking') { a.notify(); a.attend('talking', ms); }
      else a.attend(why, ms);
    },
    mouth: () => {},
    motion: () => {},
    frame: (zoom, lift) => { framing = { zoom: clamp(Number(zoom) || 1, 0.5, 3), lift: clamp(Number(lift) || 0, -1, 1) }; applyFraming(); },
  };
  document.addEventListener('DOMContentLoaded', applyFraming);
  // Alive once her first face is on the stage; failed if it never comes.
  const started = performance.now();
  const watch = setInterval(() => {
    if (document.querySelector('#avatar .face svg')) { clearInterval(watch); tell({ event: 'alive', expressions: ${HARU_EMOTIONS.length} }); return; }
    const missing = document.querySelector('#avatar .face.missing');
    if (missing || performance.now() - started > 20000) {
      clearInterval(watch);
      tell({ event: 'failed', why: missing ? 'her face could not be fetched from the server' : 'her face did not arrive' });
    }
  }, 250);
})();
</script>
<script>
${avatar}
</script>
`;
const out = resolve(new URL('.', import.meta.url).pathname, '../Haru/Resources/stage.html');
writeFileSync(out, html);
console.log(`wrote ${out}: ${html.length} chars, ${HARU_EMOTIONS.length} faces`);
