// Regenerates Haru/Resources/stage.html from the desktop's phone page, so the
// app shows the same SVG avatar the page does — crossfade, idle float, a
// wandering gaze, a blink calendar, eyes found by geometry — with no second
// copy of that code to keep in step. Run whenever electron/webpage.ts or
// emotions.ts change on the desktop side:
//
//   node scripts/sync-avatar.mjs [path/to/haru-desktop]
//
// The avatar fetches /emotions/<name>.svg itself; in the app that request
// goes through haru-stage://, which the app answers from the bundled face pack.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const desktop = resolve(process.argv[2] ?? '../haru-desktop');
const built = mkdtempSync(join(tmpdir(), 'haru-avatar-'));
// The tables live in TypeScript; the desktop's own compiler turns that one
// file into JavaScript this script can import (its only import is a type).
execFileSync(join(desktop, 'node_modules/.bin/tsc'), [
  '--outDir', built, '--module', 'es2022', '--target', 'es2022', '--moduleResolution', 'bundler',
  '--lib', 'es2022,dom', '--skipLibCheck', '--noCheck', join(desktop, 'electron/emotions.ts'),
], { stdio: 'inherit' });
const emotions = await import(pathToFileURL(join(built, 'emotions.js')).href);
const { DEFAULT_TRANSITION_MS, EASE_OUT_CSS, emotionConfig, HARU_EMOTIONS, MOOD_TO_EMOTION } = emotions;
const source = readFileSync(resolve(desktop, 'electron/webpage.ts'), 'utf8');
// The page's one hue; every colour on the stage turns with it, as on the page.
const HUE = Number((source.match(/const HUE = (\d+)/) || [])[1]);
if (!Number.isFinite(HUE)) throw new Error('could not find HUE in webpage.ts');

/** The text of a template literal in the source, evaluated with the page's own tables in scope. */
function evaluate(template) {
  const fill = new Function('DEFAULT_TRANSITION_MS', 'EASE_OUT_CSS', 'emotionConfig', 'HARU_EMOTIONS', 'MOOD_TO_EMOTION', 'HUE', 'return `' + template + '`');
  return fill(DEFAULT_TRANSITION_MS, EASE_OUT_CSS, emotionConfig, HARU_EMOTIONS, MOOD_TO_EMOTION, HUE);
}
function slice(from, to, label) {
  const start = source.indexOf(from);
  if (start < 0) throw new Error(`could not find the start of the ${label}`);
  const end = source.indexOf(to, start + from.length);
  if (end < 0) throw new Error(`could not find the end of the ${label}`);
  return source.slice(start + from.length, end + (to.startsWith('\n') ? 0 : to.length));
}

const avatar = readFileSync(resolve(desktop, 'build/lib/haru-avatar.js'), 'utf8');
const css = ''; // The shared bundle supplies its own scoped renderer styles.
// The page's theme tokens (--bg, --accent …), so the stage is lit like the page.
const root = evaluate(slice('  :root {', '\n  }', 'theme tokens'));
if (!avatar.includes('haruAvatar')) throw new Error('the avatar script does not look right');

// Sparse background sparks; all light around Haru belongs to her renderer.
function seeded(seed) { let x = seed >>> 0; return () => { x = (x * 1664525 + 1013904223) >>> 0; return x / 4294967296; }; }
const rand = seeded(HUE * 7919 + 1);
const pct = (v) => (v * 100).toFixed(1) + '%';
const sparks = Array.from({ length: 12 }, () => {
  const style = `--x:${pct(rand())};--y:${pct(0.15 + rand() * 0.85)};--s:${(1 + rand() * 2.2).toFixed(1)}px;--d:${(6 + rand() * 9).toFixed(1)}s;--t:${(-rand() * 14).toFixed(1)}s;--o:${(0.25 + rand() * 0.55).toFixed(2)};--r:${(10 + rand() * 26).toFixed(0)}px`;
  return `<i class="spark" style="${style}"></i>`;
}).join('');
const field = `${sparks}`;

const html = `<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<!-- Generated by scripts/sync-avatar.mjs from the shared Haru renderer bundle. Do not edit by hand. -->
<style>
:root {${root}
}
html, body { margin:0; height:100%; overflow:hidden; -webkit-user-select:none; -webkit-touch-callout:none; }
/* Lit like the page: the same ground and the same glow she sits in. */
body {
  position:relative; display:flex; align-items:center; justify-content:center;
  background:var(--bg);
  background-image:
    radial-gradient(120% 70% at 50% -10%, oklch(42% 0.12 var(--hue) / 0.55), transparent 60%),
    radial-gradient(90% 50% at 100% 100%, oklch(38% 0.10 calc(var(--hue) + 60) / 0.35), transparent 70%);
}
${css}
/* Her box is a share of the shorter side; BASE makes her read large at the
   app's default zoom, the More sliders still scale from there. */
#scene { position:relative; width:100%; height:100%; --base:0.88; --scene-size:calc(min(100vw, 100vh) * var(--base)); }
/* Her and her aura together: this is what the app's zoom and lift move, so
   the field behind stays put and edge to edge. */
#her { position:absolute; inset:0; display:flex; align-items:center; justify-content:center; transition:transform .3s ease; }
/* The page's own stylesheet sizes #stage for the phone page (a third of the
   width); here the stage is hers alone, so #stage takes the scene's size —
   set after the page's rules, which is what makes it win. */
#stage { padding:0; position:absolute; inset:0; }
/* Fit her entire head below the title while the keyboard is open. */
#scene.peek #her { transform:none !important; }
#scene.peek #stage { top:auto; height:160px; bottom:0; }
#scene.peek .svg-avatar-canvas { align-items:center; }
@media(prefers-reduced-motion:reduce){#her{transition:none;}}
/* Quiet background sparks stay separate from her responsive light. */
#field { position:absolute; inset:0; overflow:hidden; pointer-events:none; --lift:1; }
#field i { position:absolute; display:block; border-radius:50%; }
#field .spark { left:var(--x); top:var(--y); width:var(--s); height:var(--s); background:oklch(94% 0.06 var(--hue)); box-shadow:0 0 6px 1px oklch(86% 0.12 var(--hue) / 0.7); opacity:0; animation:twinkle var(--d) ease-in-out infinite; animation-delay:var(--t); }
@keyframes twinkle { 0% { opacity:0; transform:translateY(0) scale(.6); } 35% { opacity:calc(var(--o) * var(--lift)); transform:translateY(calc(var(--r) * -.4)) scale(1); } 70% { opacity:calc(var(--o) * .7 * var(--lift)); } 100% { opacity:0; transform:translateY(calc(var(--r) * -1)) scale(.5); } }
@media (prefers-reduced-motion: reduce) { #field .spark { animation:none !important; opacity:calc(var(--o) * .6); } }
/* Her shared renderer owns the moving, breathing, audio-reactive halo. */
/* Avoid repainting nested filtered SVG surfaces in iOS WebKit. The feathered
   gradient still follows the renderer's breath, movement and speech envelope. */
#stage .svg-avatar-canvas #avatar-body { filter:none; }
#stage .svg-avatar-canvas .avatar-rest::before { filter:none; will-change:auto;
  background:radial-gradient(ellipse closest-side at 50% 56%,rgb(255 172 205 / .38) 0%,rgb(239 148 207 / .22) 25%,rgb(185 154 255 / .09) 48%,rgb(185 154 255 / .025) 68%,rgb(185 154 255 / 0) 90%); }
</style>
<div id="scene"><div id="field">${field}</div><div id="her"><section id="stage"></section></div></div>
<script>
(() => {
  const tell = (message) => { try { window.webkit.messageHandlers.stage.postMessage(message); } catch (e) {} };
  window.addEventListener('error', (e) => tell({ event: 'failed', why: (e && e.message) || 'a script error' }));
  const clamp = (v, lo, hi) => (v < lo ? lo : v > hi ? hi : v);
  // The app speaks to window.haruStage; this hands it on to the page's
  // avatar. Zoom scales her box; lift moves her up by a share of the stage.
  let framing = { zoom: 1, lift: 0, scale: 1 };
  let face = 'neutral';
  const native = window.haruNative = { mouth: 0, speakingUntil: 0, peek: false, attachment: false };
  let attachmentTimer;
  const present = () => { const a = window.haruAvatar; if (!a) return; a.express(native.attachment ? 'curious' : native.peek ? 'attentive' : face); a.attend(native.attachment ? 'attachment' : native.peek ? 'typing' : 'here', native.peek ? 3600000 : 450); };
  native.ready = present;
  const applyFraming = () => {
    const scene = document.getElementById('scene');
    const her = document.getElementById('her');
    if (!scene || !her) return;
    scene.style.setProperty('--scene-size', 'calc(min(100vw, 100vh) * var(--base) * ' + framing.zoom + ')');
    scene.classList.toggle('peek', native.peek);
    // Scale rides the same transition as the lift, so the app's compact mode
    // (typing) shrinks her smoothly with the stage rather than in one jump.
    her.style.transform = 'translateY(' + (-framing.lift * 100).toFixed(1) + '%) scale(' + (framing.scale * framing.zoom).toFixed(3) + ')';
  };
  const speaking = (ms) => { native.speakingUntil = performance.now() + ms; };
  window.haruStage = {
    express: (name) => { if (name) face = name; const a = window.haruAvatar; if (a && !native.peek && !native.attachment) a.express(face); },
    attend: (why, ms) => {
      const a = window.haruAvatar;
      if (why === 'attachment') {
        clearTimeout(attachmentTimer); native.attachment = true; present();
        attachmentTimer = setTimeout(() => { native.attachment = false; present(); }, clamp(Number(ms) || 4200, 500, 8000));
        return;
      }
      if (why === 'typing' && native.attachment) { clearTimeout(attachmentTimer); native.attachment = false; present(); }
      if (why === 'talking') speaking(ms === undefined ? 1500 : Number(ms) || 0);
      if (!a) return;
      if (why === 'thinking') a.think();
      else if (why === 'talking') { a.notify(); a.attend('talking', ms); }
      else a.attend(why, native.peek && why === 'typing' ? 3600000 : ms);
    },
    mouth: (level) => { native.mouth = clamp(Number(level) || 0, 0, 1); native.speakingUntil = performance.now() + 450; },
    tap: () => window.haruAvatar?.tap(),
    motion: () => {},
    frame: (zoom, lift, scale, peek) => { const changed = native.peek !== !!peek; native.peek = !!peek; framing = { zoom: clamp(Number(zoom) || 1, 0.5, 3), lift: clamp(Number(lift) || 0, -1, 1), scale: clamp(Number(scale) || 1, 0.2, 1) }; applyFraming(); if (changed) present(); },
  };
  document.addEventListener('DOMContentLoaded', applyFraming);
  // Alive once her first face is on the stage; failed if it never comes.
  const started = performance.now();
  const watch = setInterval(() => {
    if (document.querySelector('#avatar .face svg')) { clearInterval(watch); tell({ event: 'alive', expressions: ${HARU_EMOTIONS.length} }); return; }
    const missing = document.querySelector('#avatar .face.missing');
    if (missing || performance.now() - started > 20000) {
      clearInterval(watch);
      tell({ event: 'failed', why: missing ? 'her face could not be fetched from the server' : 'her face did not arrive' });
    }
  }, 250);
})();
</script>
<script>
${avatar}
</script>
`;
const out = resolve(new URL('.', import.meta.url).pathname, '../Haru/Resources/stage.html');
const faces = resolve(out, '../emotions');
mkdirSync(faces, { recursive: true });
for (const name of HARU_EMOTIONS) {
  copyFileSync(resolve(desktop, 'build/emotions', emotionConfig[name].file), resolve(faces, name + '.svg'));
}
writeFileSync(out, html);
console.log(`wrote ${out}: ${html.length} chars, ${HARU_EMOTIONS.length} faces`);
