// Regenerates Haru/Resources/stage.html from the desktop's phone page, so the
// app shows the same SVG avatar the page does — crossfade, idle float, a
// wandering gaze, a blink calendar, eyes found by geometry — with no second
// copy of that code to keep in step. Run whenever electron/webpage.ts or
// emotions.ts change on the desktop side:
//
//   node scripts/sync-avatar.mjs [path/to/haru-desktop]
//
// The avatar fetches /emotions/<name>.svg itself; in the app that request
// goes through haru-stage://, which the app answers from her server.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const desktop = resolve(process.argv[2] ?? '../haru-desktop');
const built = mkdtempSync(join(tmpdir(), 'haru-avatar-'));
// The tables live in TypeScript; the desktop's own compiler turns that one
// file into JavaScript this script can import (its only import is a type).
execFileSync(join(desktop, 'node_modules/.bin/tsc'), [
  '--outDir', built, '--module', 'es2022', '--target', 'es2022', '--moduleResolution', 'bundler',
  '--lib', 'es2022,dom', '--skipLibCheck', '--noEmitOnError', 'false', join(desktop, 'electron/emotions.ts'),
], { stdio: 'inherit' });
const emotions = await import(pathToFileURL(join(built, 'emotions.js')).href);
const { DEFAULT_TRANSITION_MS, EASE_OUT_CSS, emotionConfig, HARU_EMOTIONS, MOOD_TO_EMOTION } = emotions;
const source = readFileSync(resolve(desktop, 'electron/webpage.ts'), 'utf8');
// The page's one hue; every colour on the stage turns with it, as on the page.
const HUE = Number((source.match(/const HUE = (\d+)/) || [])[1]);
if (!Number.isFinite(HUE)) throw new Error('could not find HUE in webpage.ts');

/** The text of a template literal in the source, evaluated with the page's own tables in scope. */
function evaluate(template) {
  const fill = new Function('DEFAULT_TRANSITION_MS', 'EASE_OUT_CSS', 'emotionConfig', 'HARU_EMOTIONS', 'MOOD_TO_EMOTION', 'HUE', 'return `' + template + '`');
  return fill(DEFAULT_TRANSITION_MS, EASE_OUT_CSS, emotionConfig, HARU_EMOTIONS, MOOD_TO_EMOTION, HUE);
}
function slice(from, to, label) {
  const start = source.indexOf(from);
  if (start < 0) throw new Error(`could not find the start of the ${label}`);
  const end = source.indexOf(to, start + from.length);
  if (end < 0) throw new Error(`could not find the end of the ${label}`);
  return source.slice(start + from.length, end + (to.startsWith('\n') ? 0 : to.length));
}

const avatar = evaluate(slice('const AVATAR = `', '\n`;', 'avatar script'));
const css = evaluate(slice('  /* Her, on stage:', '#avatar .face { transition:none !important; } }', 'avatar styles'));
// The page's theme tokens (--bg, --accent …), so the stage is lit like the page.
const root = evaluate(slice('  :root {', '\n  }', 'theme tokens'));
if (!avatar.includes('window.haruAvatar')) throw new Error('the avatar script does not look right');

// The ambient field behind her: soft orbs that drift, sparks that rise and
// twinkle, a glow at her feet. Placed by a seeded generator so the file is
// the same every sync; sizes and speeds vary so nothing reads as a pattern.
function seeded(seed) { let x = seed >>> 0; return () => { x = (x * 1664525 + 1013904223) >>> 0; return x / 4294967296; }; }
const rand = seeded(HUE * 7919 + 1);
const pct = (v) => (v * 100).toFixed(1) + '%';
const orbs = Array.from({ length: 7 }, (_, i) => {
  const w = 90 + rand() * 170, dx = (rand() - 0.5) * 60, dy = (rand() - 0.5) * 40;
  const style = `--x:${pct(rand())};--y:${pct(rand())};--w:${w.toFixed(0)}px;--dx:${dx.toFixed(0)}px;--dy:${dy.toFixed(0)}px;--d:${(14 + rand() * 12).toFixed(1)}s;--t:${(-rand() * 20).toFixed(1)}s;--h:${((i % 3) - 1) * 40};--o:${(0.14 + rand() * 0.18).toFixed(2)}`;
  return `<i class="orb" style="${style}"></i>`;
}).join('');
const sparks = Array.from({ length: 30 }, () => {
  const style = `--x:${pct(rand())};--y:${pct(0.15 + rand() * 0.85)};--s:${(1 + rand() * 2.2).toFixed(1)}px;--d:${(6 + rand() * 9).toFixed(1)}s;--t:${(-rand() * 14).toFixed(1)}s;--o:${(0.25 + rand() * 0.55).toFixed(2)};--r:${(10 + rand() * 26).toFixed(0)}px`;
  return `<i class="spark" style="${style}"></i>`;
}).join('');
const field = `<i class="floor"></i>${orbs}${sparks}`;

const html = `<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<!-- Generated by scripts/sync-avatar.mjs from haru-desktop/electron/webpage.ts. Do not edit by hand. -->
<style>
:root {${root}
}
html, body { margin:0; height:100%; overflow:hidden; -webkit-user-select:none; -webkit-touch-callout:none; }
/* Lit like the page: the same ground and the same glow she sits in. */
body {
  position:relative; display:flex; align-items:center; justify-content:center;
  background:var(--bg);
  background-image:
    radial-gradient(120% 70% at 50% -10%, oklch(42% 0.12 var(--hue) / 0.55), transparent 60%),
    radial-gradient(90% 50% at 100% 100%, oklch(38% 0.10 calc(var(--hue) + 60) / 0.35), transparent 70%);
}
${css}
/* Her box is a share of the shorter side; BASE makes her read large at the
   app's default zoom, the More sliders still scale from there. */
#scene { position:relative; width:100%; height:100%; --base:0.88; --scene-size:calc(min(100vw, 100vh) * var(--base)); }
/* Her and her aura together: this is what the app's zoom and lift move, so
   the field behind stays put and edge to edge. */
#her { position:absolute; inset:0; display:flex; align-items:center; justify-content:center; transition:transform .3s ease; }
/* The page's own stylesheet sizes #stage for the phone page (a third of the
   width); here the stage is hers alone, so #stage takes the scene's size —
   set after the page's rules, which is what makes it win. */
#stage { padding:0; position:relative; --avatar-size:var(--scene-size); }
/* The field she stands in: orbs adrift, sparks rising, a glow at her feet.
   Slow and dim on its own; a shade brighter while she speaks. Nothing here
   moves under reduced motion. */
#field { position:absolute; inset:0; overflow:hidden; pointer-events:none; --lift:1; }
#field i { position:absolute; display:block; border-radius:50%; will-change:transform, opacity; }
#field .floor { left:50%; top:78%; width:120%; height:55%; transform:translate(-50%,-50%); border-radius:50%; background:radial-gradient(ellipse at center, oklch(55% 0.13 var(--hue) / 0.22), oklch(40% 0.10 calc(var(--hue) + 30) / 0.08) 45%, transparent 70%); filter:blur(22px); }
#field .orb { left:var(--x); top:var(--y); width:var(--w); aspect-ratio:1; transform:translate(-50%,-50%); background:radial-gradient(circle, oklch(72% 0.13 calc(var(--hue) + var(--h)) / var(--o)), oklch(60% 0.12 calc(var(--hue) + var(--h)) / calc(var(--o) * 0.5)) 40%, transparent 70%); filter:blur(16px); animation:drift var(--d) ease-in-out infinite alternate; animation-delay:var(--t); }
#field .spark { left:var(--x); top:var(--y); width:var(--s); height:var(--s); background:oklch(94% 0.06 var(--hue)); box-shadow:0 0 6px 1px oklch(86% 0.12 var(--hue) / 0.7); opacity:0; animation:twinkle var(--d) ease-in-out infinite; animation-delay:var(--t); }
@keyframes drift { from { transform:translate(-50%,-50%) translate(0,0) scale(1); } to { transform:translate(-50%,-50%) translate(var(--dx), var(--dy)) scale(1.15); } }
@keyframes twinkle { 0% { opacity:0; transform:translateY(0) scale(.6); } 35% { opacity:calc(var(--o) * var(--lift)); transform:translateY(calc(var(--r) * -.4)) scale(1); } 70% { opacity:calc(var(--o) * .7 * var(--lift)); } 100% { opacity:0; transform:translateY(calc(var(--r) * -1)) scale(.5); } }
#scene.live #field { --lift:1.6; }
@media (prefers-reduced-motion: reduce) { #field .orb, #field .spark { animation:none !important; } #field .spark { opacity:calc(var(--o) * .6); } }
/* Her voice, as light: a glow behind her that swells with the level of what
   she is saying, and rings that spread from her while she speaks. Driven from
   the app's audio meter through haruStage.mouth; dark and still otherwise. */
#aura { position:absolute; inset:0; display:flex; align-items:center; justify-content:center; pointer-events:none; --voice:0; --live:0; }
#aura i { position:absolute; display:block; width:var(--scene-size); aspect-ratio:1; border-radius:50%; will-change:transform, opacity; }
#aura .glow {
  background:radial-gradient(circle, oklch(82% 0.14 var(--hue) / 0.60) 0%, oklch(64% 0.13 var(--hue) / 0.30) 40%, oklch(46% 0.12 calc(var(--hue) + 40) / 0.12) 60%, transparent 72%);
  filter:blur(14px);
  opacity:calc(var(--live) * (0.28 + var(--voice) * 0.72));
  transform:scale(calc(0.92 + var(--voice) * 0.32));
  transition:opacity .35s ease, transform .09s ease-out;
}
#aura .ring { border:1.5px solid oklch(88% 0.10 var(--hue) / 0.55); opacity:0; }
#scene.live .ring { animation:ripple 2.4s cubic-bezier(.2,.6,.3,1) infinite; }
#scene.live .r2 { animation-delay:1.2s; }
@keyframes ripple { 0% { transform:scale(.80); opacity:calc(.10 + var(--voice) * .55); } 100% { transform:scale(1.55); opacity:0; } }
@media (prefers-reduced-motion: reduce) { #aura .ring { animation:none !important; } }
</style>
<div id="scene"><div id="field">${field}</div><div id="her"><div id="aura"><i class="glow"></i><i class="ring r1"></i><i class="ring r2"></i></div><section id="stage"></section></div></div>
<script>
(() => {
  const tell = (message) => { try { window.webkit.messageHandlers.stage.postMessage(message); } catch (e) {} };
  window.addEventListener('error', (e) => tell({ event: 'failed', why: (e && e.message) || 'a script error' }));
  const clamp = (v, lo, hi) => (v < lo ? lo : v > hi ? hi : v);
  // The app speaks to window.haruStage; this hands it on to the page's
  // avatar. Zoom scales her box; lift moves her up by a share of the stage.
  let framing = { zoom: 1, lift: 0, scale: 1 };
  const applyFraming = () => {
    const scene = document.getElementById('scene');
    const her = document.getElementById('her');
    if (!scene || !her) return;
    scene.style.setProperty('--scene-size', 'calc(min(100vw, 100vh) * var(--base) * ' + framing.zoom + ')');
    // Scale rides the same transition as the lift, so the app's compact mode
    // (typing) shrinks her smoothly with the stage rather than in one jump.
    her.style.transform = 'translateY(' + (-framing.lift * 100).toFixed(1) + '%) scale(' + framing.scale.toFixed(3) + ')';
  };
  // The aura follows her voice: the meter's level is the target, reached
  // quickly on the way up and let go slowly, so syllables show and pauses
  // breathe. A talking cue without audio yet keeps a low glow going.
  let voice = 0, target = 0, speakingUntil = 0, raf = 0;
  const tick = () => {
    const aura = document.getElementById('aura');
    const scene = document.getElementById('scene');
    const now = performance.now();
    if (now > speakingUntil) target = 0;
    voice += (target - voice) * (target > voice ? 0.55 : 0.10);
    if (voice < 0.005) voice = 0;
    const live = now < speakingUntil + 700;
    if (aura) {
      aura.style.setProperty('--voice', voice.toFixed(3));
      aura.style.setProperty('--live', live ? '1' : '0');
      aura.classList.toggle('live', live);
    }
    if (scene) scene.classList.toggle('live', live);
    raf = (live || voice > 0) ? requestAnimationFrame(tick) : 0;
  };
  const wake = () => { if (!raf) raf = requestAnimationFrame(tick); };
  const speaking = (ms) => { speakingUntil = Math.max(speakingUntil, performance.now() + ms); target = Math.max(target, 0.12); wake(); };
  window.haruStage = {
    express: (name) => { const a = window.haruAvatar; if (a && name) a.express(name); },
    attend: (why, ms) => {
      const a = window.haruAvatar;
      if (why === 'talking') speaking(ms === undefined ? 1500 : Number(ms) || 0);
      if (!a) return;
      if (why === 'thinking') a.think();
      else if (why === 'talking') { a.notify(); a.attend('talking', ms); }
      else a.attend(why, ms);
    },
    mouth: (level) => { target = clamp(Number(level) || 0, 0, 1); speakingUntil = Math.max(speakingUntil, performance.now() + 450); wake(); },
    motion: () => {},
    frame: (zoom, lift, scale) => { framing = { zoom: clamp(Number(zoom) || 1, 0.5, 3), lift: clamp(Number(lift) || 0, -1, 1), scale: clamp(Number(scale) || 1, 0.2, 1) }; applyFraming(); },
  };
  document.addEventListener('DOMContentLoaded', applyFraming);
  // Alive once her first face is on the stage; failed if it never comes.
  const started = performance.now();
  const watch = setInterval(() => {
    if (document.querySelector('#avatar .face svg')) { clearInterval(watch); tell({ event: 'alive', expressions: ${HARU_EMOTIONS.length} }); return; }
    const missing = document.querySelector('#avatar .face.missing');
    if (missing || performance.now() - started > 20000) {
      clearInterval(watch);
      tell({ event: 'failed', why: missing ? 'her face could not be fetched from the server' : 'her face did not arrive' });
    }
  }, 250);
})();
</script>
<script>
${avatar}
</script>
`;
const out = resolve(new URL('.', import.meta.url).pathname, '../Haru/Resources/stage.html');
writeFileSync(out, html);
console.log(`wrote ${out}: ${html.length} chars, ${HARU_EMOTIONS.length} faces`);
